# Site settings
title: Reck Meck
#email: tim.othy@mecklem.com
description: ""
baseurl: ""
url: "http://tmecklem.github.io"
username: "tmecklem"
twitter_username: "tim_mecklem"

# Build settings
markdown: kramdown
permalink: pretty
