# Site settings
title: Tim Mecklem
#email: tim.othy@mecklem.com
description: ""
baseurl: ""
url: "http://timothy.mecklem.com"
username: "tmecklem"
twitter_username: "tim_mecklem"

# Build settings
markdown: kramdown
permalink: pretty
